require("custom.plugins.lualine")
require("custom.plugins.transparent")
require("custom.plugins.themery")
require("custom.plugins.oil")
require("custom.plugins.blink")
require("custom.plugins.diagnostics") 
require("custom.plugins.lsp")
require("custom.plugins.autopairs")
