require("custom.plugins.lualine")
require("custom.plugins.oil")
require("custom.plugins.blink")
require("custom.plugins.diagnostics") 
require("custom.plugins.lsp")
require("custom.plugins.vim-tpipeline")
require("custom.plugins.autopairs")
